[versions]
java = "17" # See also: `org.gradle.jvm.toolchain.JavaLanguageVersion`
java-vendor = "AZUL" # See also: `org.gradle.jvm.toolchain.JvmVendorSpec`
kotlin = "1.9.23" # https://github.com/JetBrains/kotlin/releases
detekt = "1.23.6" # https://github.com/detekt/detekt/releases
compose = "1.6.1" # https://github.com/JetBrains/compose-multiplatform/releases
jxbrowser = "8.0.0-eap.7-test" # https://europe-maven.pkg.dev/jxbrowser/eaps/com/teamdev/jxbrowser/jxbrowser-mac/maven-metadata.xml
jxbrowser-gradlePlugin = "1.0.2" # https://github.com/TeamDev-IP/JxBrowser-Gradle-Plugin/releases
taskTree-gradlePlugin = "2.1.1" # https://github.com/dorongold/gradle-task-tree/releases

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradlePlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
jxbrowser-gradlePlugin = { module = "com.teamdev.jxbrowser:JxBrowser-Gradle-Plugin", version.ref = "jxbrowser-gradlePlugin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
taskTree-gradlePlugin = { module = "com.dorongold.plugins:task-tree", version.ref = "taskTree-gradlePlugin" }
